(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.FSVMemoryResponse=api;api.mount(document,location,navigator);}})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const themes={'family-heritage':['#6e2f36','#9a7338'],'garden-archive':['#315c43','#9a7041'],'classic-album':['#263f5c','#9b7a43'],'clean-modern':['#a04435','#a36f35']};
function themeFor(id){return themes[id]||themes['family-heritage'];}
function decodeFragment(fragment){if(!fragment)throw new Error('missing');const value=fragment.replace(/^#/,'');if(!/^[A-Za-z0-9_-]+$/.test(value)||value.length%4===1)throw new Error('invalid');const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),padded=normalized+'='.repeat((4-normalized.length%4)%4);let parsed;try{const binary=atob(padded),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));parsed=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{throw new Error('invalid');}if(!parsed||parsed.packageType!=='family-story-vault-memory-invitation'||parsed.formatVersion!==1||typeof parsed.invitationId!=='string'||typeof parsed.inviterDisplayName!=='string'||typeof parsed.vaultDisplayName!=='string'||typeof parsed.subject?.displayName!=='string'||typeof parsed.request?.questionText!=='string')throw new Error('unsupported');return parsed;}
const appLink=fragment=>'family-story-vault://invitation-link?request='+encodeURIComponent(fragment.replace(/^#/,''));
const enc=new TextEncoder(),u16=(a,v)=>a.push(v&255,v>>>8&255),u32=(a,v)=>a.push(v&255,v>>>8&255,v>>>16&255,v>>>24&255);const crcTable=(()=>{const table=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xEDB88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;})();const crc32=bytes=>{let c=0xFFFFFFFF;for(const byte of bytes)c=crcTable[(c^byte)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0;};
function contribution(invitation,name,memory,now,id){return{packageType:'family-story-vault-contribution',formatVersion:1,contributionId:id,invitationId:invitation.invitationId,exportedAt:now,contributorName:name.trim(),subject:invitation.subject,requestedQuestion:invitation.request.questionText,story:{title:'A memory from '+name.trim(),content:memory.trim(),questionId:invitation.request.questionId,questionText:invitation.request.questionText,places:[],mediaAssetIds:[],createdAt:now,updatedAt:now},mediaAssets:[],files:[]};}
function zipContribution(data){const name=enc.encode('data/contribution.json'),body=enc.encode(JSON.stringify(data)),crc=crc32(body),local=[];u32(local,0x04034b50);u16(local,20);u16(local,0);u16(local,0);u16(local,0);u16(local,0);u32(local,crc);u32(local,body.length);u32(local,body.length);u16(local,name.length);u16(local,0);local.push(...name,...body);const central=[];u32(central,0x02014b50);u16(central,20);u16(central,20);u16(central,0);u16(central,0);u16(central,0);u16(central,0);u32(central,crc);u32(central,body.length);u32(central,body.length);u16(central,name.length);u16(central,0);u16(central,0);u16(central,0);u16(central,0);u32(central,0);u32(central,0);central.push(...name);const end=[];u32(end,0x06054b50);u16(end,0);u16(end,0);u16(end,1);u16(end,1);u32(end,central.length);u32(end,local.length);u16(end,0);return new Uint8Array([...local,...central,...end]);}
const safe=value=>(value.normalize?value.normalize('NFKD'):value).replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'Family-Member';
function mount(doc,loc,nav){let invitation;const error=doc.getElementById('request-error');try{invitation=decodeFragment(loc.hash);}catch{error.hidden=false;return;}['request-card','write-card','app-card'].forEach(id=>{doc.getElementById(id).hidden=false;});doc.getElementById('requester').textContent=invitation.inviterDisplayName+' has asked you to share a memory';doc.getElementById('vault').textContent=invitation.vaultDisplayName;doc.getElementById('subject').textContent=invitation.subject.displayName;doc.getElementById('question').textContent='“'+invitation.request.questionText+'”';doc.getElementById('personal-message').textContent=invitation.personalMessage||'';if(invitation.recipientDisplayName)doc.getElementById('contributor-name').value=invitation.recipientDisplayName;const colors=themeFor(invitation.senderThemeId);doc.documentElement.style.setProperty('--request-primary',colors[0]);doc.documentElement.style.setProperty('--request-accent',colors[1]);doc.getElementById('open-app').href=appLink(loc.hash);let objectUrl;doc.getElementById('response-form').addEventListener('submit',async event=>{event.preventDefault();const name=doc.getElementById('contributor-name').value.trim(),memory=doc.getElementById('memory').value.trim(),status=doc.getElementById('status'),download=doc.getElementById('download');if(!name||!memory){status.className='error';status.textContent=!name?'Please enter your name.':'Please write your memory.';return;}const now=new Date().toISOString(),id='contribution-browser-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),blob=new Blob([zipContribution(contribution(invitation,name,memory,now,id))],{type:'application/vnd.familystoryvault.contribution'}),filename='Memory-Response-'+safe(name)+'.fsvcontribution',file=typeof File==='function'?new File([blob],filename,{type:'application/vnd.familystoryvault.contribution'}):undefined;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);download.href=objectUrl;download.download=filename;download.hidden=false;status.className='success';status.textContent='Your memory is ready. Send it back to '+invitation.inviterDisplayName+'.';if(file&&nav.share&&nav.canShare&&nav.canShare({files:[file]})){try{await nav.share({files:[file],title:'Family Story Vault Memory Response'});}catch(cause){if(cause?.name!=='AbortError'){status.className='error';status.textContent='Sharing was unavailable. Use Download Memory Response instead.';}}}});}
return{themeFor,decodeFragment,appLink,contribution,zipContribution,mount};});
